Unbreak linting
eslint will traverse all the way up to the root of the filesystem
looking for `.eslintrc` and `package.json` files from which to load
options.

This was causing things to explode here because I am nested inside the
Relay repo, which uses Jest, but I am not using Jest locally. So, it
would traverse up and go boom like this:

    relay/contrib/lightweight-results/node_modules/eslint/lib/eslint.js:394
                if (config.env[env] && environments[env].ecmaFeatures) {
                                                        ^

    TypeError: Cannot read property 'ecmaFeatures' of undefined

Because `env` would be "jest", but `environments` had no such property.

Stop the madness by forcibly turning off Jest. No idea what other
settings I am inheriting from higher levels but hopefully it is nothing
too insane.

See: http://eslint.org/docs/user-guide/configuring